<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <LangVersion>latest</LangVersion>
    <TargetFramework>net8.0</TargetFramework>
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="BenchmarkDotNet.Attributes" />
    <Using Include="BenchmarkDotNet.Order" />
    <Using Include="BenchmarkDotNet.Configs" />
    <Using Include="BenchmarkDotNet.Jobs" />
    <Using Include="BenchmarkDotNet.Diagnosers" />
    <Using Include="BenchmarkDotNet.Loggers" />
    <Using Include="BenchmarkDotNet.Diagnostics.Windows.Configs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.14.0" />
    <PackageReference Include="BenchmarkDotNet.Diagnostics.Windows" Version="0.14.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\FastLazy\FastLazy.csproj" />
  </ItemGroup>
</Project>
